---
title: "Midcourse EDA"
output: html_notebook
---
```{r}
library(tidyverse)
library(dplyr)
#install.packages("ggplot2")
#install.packages("readr")
library(ggplot2)
install.packages("randomNames")
library(randomNames)
```

## Midcourse EDA


1.

```{r}
sales <- read.csv('../data/read_all_orders_2019_2024.csv')
sales
```



```{r}
sales_2024 <- sales |>
  filter(Year == 2024)
sales_2024
```



```{r}
    ggplot(sales_2024, aes(x = S_Cons_Order_Class, y = Adj_Revenue)) +
      geom_boxplot()
```



```{r}
sales_2024 |> 
  filter(S_Cons_Order_Class == "In-Stock") |> 
  ggplot(aes(x = Adj_Revenue, fill = S_Cons_Order_Class)) + 
  geom_histogram(bins = 100)
```



```{r}
names <- randomNames(1754)

names_df <- data.frame(CustomerName = names)

write.csv(names_df, "names.csv", row.names = FALSE)
```



```{r}

```



```{r}

```


```{r}

```


```{r}

```

10. 

```{r}

```



```{r}

```

12. 

```{r}


```


```{r}


```


```{r}

```



```{r}

```



```{r}

```


```{r}


```




```{r}

```

 

```{r}

```



```{r}

```



```{r}


```



```{r}

```



```{r}


```

```{r}


```

```{r}

```



```{r}

```


```{r}

```


```{r}

```